export const CODE_IMPORT_TEMPLATES = {
  registration_code: {
    fileName: 'registration-code-import-template.csv',
    columns: [
      'code',
      'name',
      'product_key',
      'max_uses',
      'status',
      'expires_at',
      'batch_no',
      'campaign_name',
      'channel',
      'source_platform',
      'external_order_no',
      'notes',
    ],
    rows: [
      {
        code: 'REG-DEMO-001',
        name: 'Registration code sample',
        product_key: 'novel_product',
        max_uses: 1,
        status: 'enabled',
        expires_at: '2026-12-31 23:59:59',
        batch_no: 'REG-2026-04',
        campaign_name: 'Auto delivery',
        channel: 'xianyu',
        source_platform: 'Xianyu',
        external_order_no: 'XY202604090001',
        notes: 'Sample data, can be deleted',
      },
    ],
  },
  subscription_code: {
    fileName: 'subscription-code-import-template.csv',
    columns: [
      'code',
      'name',
      'plan_id',
      'max_uses',
      'status',
      'expires_at',
      'batch_no',
      'campaign_name',
      'channel',
      'source_platform',
      'external_order_no',
      'notes',
    ],
    rows: [
      {
        code: 'SUB-DEMO-001',
        name: 'Monthly subscription code',
        plan_id: 1,
        max_uses: 1,
        status: 'enabled',
        expires_at: '2026-12-31 23:59:59',
        batch_no: 'SUB-2026-04',
        campaign_name: 'Taobao subscription',
        channel: 'taobao',
        source_platform: 'Taobao',
        external_order_no: 'TB202604090101',
        notes: 'Please change plan_id to actual plan ID',
      },
    ],
  },
} as const

export type CodeImportTemplateKey = keyof typeof CODE_IMPORT_TEMPLATES
